# Generated by Django 5.0.6 on 2024-06-10 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Host'), (2, 'User')], verbose_name='Role')),
                ('group_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_app_user', models.BooleanField(default=False, verbose_name='Is App User')),
                ('is_admin_owner', models.BooleanField(default=False, verbose_name='Is Admin Owner')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Activated'), (2, 'Deactivated')], default=1, verbose_name='Activation Status')),
                ('is_new', models.BooleanField(default=True, verbose_name='New User')),
                ('referral_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=8)),
                ('email', models.EmailField(default='example@example.com', max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
